#!/bin/bash
# Run discovery phase for kvm_vhost_tun_latency_details.py.
#
# This tool requires a discovery phase to identify vhost worker threads
# before measurement. Discovery depends on traffic flowing through the
# vnet interface - either background traffic or generated by measure.py.
#
# Required environment variables:
#   SENDER_VM_SSH, SENDER_VM_IP, SENDER_HOST_SSH, SEND_VNET_IF
#   RECEIVER_VM_SSH, RECEIVER_VM_IP, RECEIVER_HOST_SSH, RECV_VNET_IF
#   DISCOVERY_DURATION (default: 5)
#
# Output:
#   Sender Host: /tmp/kvm-tun-send-profile.json
#   Receiver Host: /tmp/kvm-tun-recv-profile.json

set -e

# Default values
DISCOVERY_DURATION=${DISCOVERY_DURATION:-30}

# Check required variables
for VAR in SENDER_VM_SSH SENDER_VM_IP SENDER_HOST_SSH SEND_VNET_IF \
           RECEIVER_VM_SSH RECEIVER_VM_IP RECEIVER_HOST_SSH RECV_VNET_IF \
           MEASUREMENT_DIR; do
    if [ -z "${!VAR}" ]; then
        echo "Error: ${VAR} is not set" >&2
        exit 1
    fi
done

# Ensure measurement directory exists
mkdir -p "${MEASUREMENT_DIR}"
CMDLOG="${MEASUREMENT_DIR}/commands.log"

echo "Running discovery phase for kvm_vhost_tun_latency..."
echo "  Discovery duration: ${DISCOVERY_DURATION}s"

# Log to commands.log
echo "" >> ${CMDLOG}
echo "=== Discovery Phase ===" >> ${CMDLOG}
echo "Timestamp: $(date)" >> ${CMDLOG}
echo "DISCOVERY_DURATION=${DISCOVERY_DURATION}s" >> ${CMDLOG}
echo "" >> ${CMDLOG}

# Run both discoveries in PARALLEL to minimize total time
echo ""
echo "=== Running Discovery on Both Hosts in Parallel ==="
echo ""
echo "[1/2] Sender Host Discovery (for outgoing ICMP request)"
echo "      Device: ${SEND_VNET_IF}"
echo "      Flow: proto=icmp,src=${SENDER_VM_IP},dst=${RECEIVER_VM_IP}"
echo ""
echo "[2/2] Receiver Host Discovery (for outgoing ICMP reply)"
echo "      Device: ${RECV_VNET_IF}"
echo "      Flow: proto=icmp,src=${RECEIVER_VM_IP},dst=${SENDER_VM_IP}"
echo ""
echo "Duration: ${DISCOVERY_DURATION}s (running in parallel)"

# Build commands
SEND_CMD="sudo python3 /tmp/kvm_vhost_tun_latency_details.py --mode discover --device ${SEND_VNET_IF} --flow 'proto=icmp,src=${SENDER_VM_IP},dst=${RECEIVER_VM_IP}' --duration ${DISCOVERY_DURATION} --out /tmp/kvm-tun-send-profile.json"
RECV_CMD="sudo python3 /tmp/kvm_vhost_tun_latency_details.py --mode discover --device ${RECV_VNET_IF} --flow 'proto=icmp,src=${RECEIVER_VM_IP},dst=${SENDER_VM_IP}' --duration ${DISCOVERY_DURATION} --out /tmp/kvm-tun-recv-profile.json"

# Log commands
echo "[Parallel] Sender Host Discovery" >> ${CMDLOG}
echo "      CMD: ssh ${SENDER_HOST_SSH} '${SEND_CMD}'" >> ${CMDLOG}
echo "[Parallel] Receiver Host Discovery" >> ${CMDLOG}
echo "      CMD: ssh ${RECEIVER_HOST_SSH} '${RECV_CMD}'" >> ${CMDLOG}

# Run both discoveries in parallel
ssh ${SENDER_HOST_SSH} "${SEND_CMD}" &
SEND_PID=$!

ssh ${RECEIVER_HOST_SSH} "${RECV_CMD}" &
RECV_PID=$!

# Wait for both to complete
echo ""
echo "Waiting for both discoveries to complete..."
wait ${SEND_PID}
SEND_RC=$?
wait ${RECV_PID}
RECV_RC=$?

# Check results
if [ ${SEND_RC} -eq 0 ]; then
    echo "  -> Sender Host: Profile saved to /tmp/kvm-tun-send-profile.json"
    echo "      Result: Sender profile saved" >> ${CMDLOG}
else
    echo "  -> Sender Host: Discovery FAILED (rc=${SEND_RC})"
    echo "      Result: Sender discovery FAILED" >> ${CMDLOG}
fi

if [ ${RECV_RC} -eq 0 ]; then
    echo "  -> Receiver Host: Profile saved to /tmp/kvm-tun-recv-profile.json"
    echo "      Result: Receiver profile saved" >> ${CMDLOG}
else
    echo "  -> Receiver Host: Discovery FAILED (rc=${RECV_RC})"
    echo "      Result: Receiver discovery FAILED" >> ${CMDLOG}
fi

echo ""
echo "Discovery phase complete (parallel execution)."
echo "" >> ${CMDLOG}
echo "=== Discovery Phase Complete ===" >> ${CMDLOG}
